name: Caller Reusable Workflow

on: [push]
jobs:
  echo-start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  call-workflow-passing-data:
    needs: [echo-start]
    uses: Armakuji/reusable-workflow/.github/workflows/reusable-workflow.yaml@main
    secrets:
      CALLER_TOKEN: ${{ secrets.CALLER_TOKEN }}
